# Generated by Django 4.1.2 on 2022-11-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant", name="img", field=models.URLField(default=""),
        ),
    ]
