# Generated by Django 4.1.2 on 2022-12-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_alter_restaurant_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews", name="review", field=models.TextField(),
        ),
    ]
