# Generated by Django 4.1.2 on 2022-12-11 06:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_alter_restaurant_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="rev",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(null=True, unique=True),
                default=1,
                size=None,
            ),
            preserve_default=False,
        ),
    ]
