# Generated by Django 4.1.2 on 2022-12-11 06:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_restaurant_rev"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="rev",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), size=None
            ),
        ),
    ]
