# Generated by Django 4.1.2 on 2022-12-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_alter_restaurant_rev"),
    ]

    operations = [
        migrations.RemoveField(model_name="restaurant", name="rev",),
        migrations.AlterField(
            model_name="reviews", name="review", field=models.TextField(),
        ),
    ]
