# Generated by Django 4.1.2 on 2022-10-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0005_reviews_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews", name="review", field=models.TextField(default=""),
        ),
    ]
