# Generated by Django 4.1.2 on 2022-10-31 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0006_alter_reviews_review"),
    ]

    operations = [
        migrations.RemoveField(model_name="reviews", name="user",),
    ]
