# Generated by Django 4.1.2 on 2022-11-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0007_remove_reviews_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="desc",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
