# Generated by Django 4.1.2 on 2022-11-02 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0008_restaurant_desc"),
    ]

    operations = [
        migrations.RemoveField(model_name="restaurant", name="rating",),
    ]
