# Generated by Django 4.1.2 on 2022-11-02 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('address_url', models.URLField(blank=True)),
                ('kecamatan', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('capacity_timeslot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan'), ('Lainnya', 'Lainnya')], max_length=40)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointed_by_name', models.CharField(max_length=80)),
                ('facility_name', models.CharField(max_length=50)),
                ('date', models.DateField(help_text='YYYY-MM-DD')),
                ('timeslot', models.CharField(choices=[('08:00 - 08:30', '08:00 - 08:30'), ('08:30 - 09:00', '08:30 - 09:00'), ('09:00 - 09:30', '09:00 - 09:30'), ('09:30 - 10.00', '09:30 - 10.00'), ('10:00 - 10:30', '10:00 - 10:30'), ('10:30 - 11:00', '10:30 - 11:00'), ('11:00 - 11:30', '11:00 - 11:30'), ('11:30 - 12.00', '11:30 - 12.00')], max_length=20)),
                ('appointed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesehatan.patient')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kesehatan.healthfacility')),
            ],
        ),
    ]
