# Generated by Django 4.1.2 on 2022-11-02 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kesehatan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthfacility',
            name='capacity_now',
        ),
    ]
