# Generated by Django 4.1 on 2022-10-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kependudukan', '0003_alter_requestktp_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestktp',
            name='kecamatan',
            field=models.CharField(choices=[('Beji', 'Beji'), ('Pancoran Mas', 'Pancoran Mas'), ('Cipayung', 'Cipayung'), ('Sukmajaya', 'Sukmajaya'), ('Cilodong', 'Cilodong'), ('Limo', 'Limo'), ('Cinere', 'Cinere'), ('Cimanggis', 'Cimanggis'), ('Tapos', 'Tapos'), ('Sawangan', 'Sawangan'), ('Bojong Sari', 'Bojong Sari')], max_length=255),
        ),
        migrations.AlterField(
            model_name='requestktp',
            name='kelurahan',
            field=models.CharField(choices=[('Beji', 'Beji'), ('Beji Timur', 'Beji Timur'), ('Kemiri Muka', 'Kemiri Muka'), ('Pondok Cina', 'Pondok Cina'), ('Kukusan', 'Kukusan'), ('Tanah Baru', 'Tanah Baru'), ('Pancoran Mas', 'Pancoran Mas'), ('Depok', 'Depok'), ('Depok Jaya', 'Depok Jaya'), ('Rangkapan Jaya', 'Rangkapan Jaya'), ('Rangkapan Jaya Baru', 'Rangkapan Jaya Baru'), ('Mampang', 'Mampang'), ('Cipayung', 'Cipayung'), ('Cipayung Jaya', 'Cipayung Jaya'), ('Ratu Jaya', 'Ratu Jaya'), ('Bojong Pondok Terong', 'Bojong Pondok Terong'), ('Pondok Jaya', 'Pondok Jaya'), ('Sukmajaya', 'Sukmajaya'), ('Mekar Jaya', 'Mekar Jaya'), ('Bakti Jaya', 'Bakti Jaya'), ('Abadi Jaya', 'Abadi Jaya'), ('Tirta Jaya', 'Tirta Jaya'), ('Cisalak', 'Cisalak'), ('Sukamaju', 'Sukamaju'), ('Cilodong', 'Cilodong'), ('Kalibaru', 'Kalibaru'), ('Kalimulya', 'Kalimulya'), ('Jatimulya', 'Jatimulya'), ('Limo', 'Limo'), ('Meruyung', 'Meruyung'), ('Grogol', 'Grogol'), ('Krukut', 'Krukut'), ('Cinere', 'Cinere'), ('Gandul', 'Gandul'), ('Pengkalan Jati', 'Pengkalan Jati'), ('Pangkalan Jati Baru', 'Pangkalan Jati Baru'), ('Cisalak Pasar', 'Cisalak Pasar'), ('Mekarsari', 'Mekarsari'), ('Tugu', 'Tugu'), ('Pasir Gunung Selatan', 'Pasir Gunung Selatan'), ('Harjamukti', 'Harjamukti'), ('Curug', 'Curug'), ('Tapos', 'Tapos'), ('Leuwinanggung', 'Leuwinanggung'), ('Sukatani', 'Sukatani'), ('Sukamaju Baru', 'Sukamaju Baru'), ('Jatijajar', 'Jatijajar'), ('Cilangkap', 'Cilangkap'), ('Cimpaeun', 'Cimpaeun'), ('Sawangan', 'Sawangan'), ('Kedaung', 'Kedaung'), ('Cinangka', 'Cinangka'), ('Sawangan Baru', 'Sawangan Baru'), ('Bedahan', 'Bedahan'), ('Pengasinan', 'Pengasinan'), ('Pasir Putih', 'Pasir Putih'), ('Bojong Sari', 'Bojong Sari'), ('Bojongsari Baru', 'Bojongsari Baru'), ('Serua', 'Serua'), ('Pondok Petir', 'Pondok Petir'), ('Curug', 'Curug'), ('Duren Mekar', 'Duren Mekar'), ('Duren Seribu', 'Duren Seribu')], max_length=255),
        ),
        migrations.AlterField(
            model_name='requestktp',
            name='permohonan',
            field=models.CharField(choices=[('Baru', 'Baru'), ('Penggantian', 'Penggantian')], max_length=255),
        ),
        migrations.AlterField(
            model_name='requestktp',
            name='schedule_time',
            field=models.CharField(choices=[('08:00 - 08:15', '08:00 - 08:15'), ('08:15 - 08:30', '08:15 - 08:30'), ('08:30 - 08:45', '08:30 - 08:45'), ('08:45 - 09.00', '08:45 - 09.00'), ('09:00 - 09:15', '09:00 - 09:15'), ('09:15 - 09:30', '09:15 - 09:30'), ('09:30 - 09:45', '09:30 - 09:45'), ('09:45 - 10.00', '09:45 - 10.00'), ('10:00 - 10:15', '10:00 - 10:15'), ('10:15 - 10:30', '10:15 - 10:30'), ('10:30 - 10:45', '10:30 - 10:45'), ('10:45 - 11.00', '10:45 - 11.00'), ('11:00 - 11:15', '11:00 - 11:15'), ('11:15 - 11:30', '11:15 - 11:30'), ('11:30 - 11:45', '11:30 - 11:45'), ('11:45 - 12.00', '11:45 - 12.00'), ('13:00 - 13:15', '13:00 - 13:15'), ('13:15 - 13:30', '13:15 - 13:30'), ('13:30 - 13:45', '13:30 - 13:45'), ('13:45 - 14.00', '13:45 - 14.00'), ('14:00 - 14:15', '14:00 - 14:15'), ('14:15 - 14:30', '14:15 - 14:30'), ('14:30 - 14:45', '14:30 - 14:45'), ('14:45 - 15.00', '14:45 - 15.00')], max_length=255),
        ),
    ]
