# Generated by Django 4.1 on 2022-10-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kependudukan', '0004_alter_requestktp_kecamatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestktp',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
