# Generated by Django 4.1 on 2022-10-28 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kependudukan', '0005_alter_requestktp_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestktp',
            name='kota',
            field=models.CharField(default='Depok', max_length=255),
        ),
        migrations.AddField(
            model_name='requestktp',
            name='provinsi',
            field=models.CharField(default='Jawa Barat', max_length=255),
        ),
        migrations.AlterField(
            model_name='requestktp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
