# Generated by Django 4.1 on 2022-10-28 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kependudukan', '0006_requestktp_kota_requestktp_provinsi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestktp',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
