# Generated by Django 3.2.9 on 2022-11-01 13:28

from django.db import migrations, models
import perpustakaan.models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0003_auto_20221101_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(upload_to=perpustakaan.models.Book.file_location),
        ),
    ]
