# Generated by Django 4.1.2 on 2022-11-02 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0004_alter_book_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='BookFavorite',
        ),
    ]
